//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minhaGeladeira
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Lista_Compra
    {
        public int Id { get; set; }
        public int Id_Grupo { get; set; }
        public int Id_Produto { get; set; }
        public int Quantidade { get; set; }
        public int Urgencia { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
