//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minhaGeladeira
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class minhaGeladeiraEntities : DbContext
    {
        public minhaGeladeiraEntities()
            : base("name=minhaGeladeiraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grupo> Grupoes { get; set; }
        public virtual DbSet<Item_Geladeira> Item_Geladeira { get; set; }
        public virtual DbSet<Item_Lista_Compra> Item_Lista_Compra { get; set; }
        public virtual DbSet<Membro_Grupo> Membro_Grupo { get; set; }
        public virtual DbSet<Produto> Produtoes { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
