//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace minhaGeladeira
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class minhaGeladeiraEntities : DbContext
    {
        public minhaGeladeiraEntities()
            : base("name=minhaGeladeiraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grupo> Grupos { get; set; }
        public virtual DbSet<Item_Geladeira> ItensGeladeira { get; set; }
        public virtual DbSet<Item_Lista_Compra> ItensListaCompra { get; set; }
        public virtual DbSet<Membro_Grupo> MembrosGrupo { get; set; }
        public virtual DbSet<Produto> Produtos { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
